'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

# While observing the above series, I found out that the 2nd term, the 5th term, and the 8th term are even.
#And then the next even term is the 11th term.
#Therefore, the term numbers are forming an Arithmetic Progression with the first term being 2 and the common difference is 3

a=1
b=2
sum=0 #Stores sum of even-valued terms. Initializing sum to 0
while b<4*10**6: #a and b are the first two terms and we are obtaining every third term as the even-valued term's term numbers are in A.P.
    sum+=b
    temp=b
    b=3*b+2*a #value of term that is 3 terms distant from the previous term of b
    print(a)
    a=2*temp+a #Similar with a

print("The sum of the even-valued terms is ",sum)
    
